openapi: 3.1.0
info:
  contact:
    email: info@localstack.cloud
    name: LocalStack Support
    url: https://www.localstack.cloud/contact
  summary: The LocalStack REST API exposes functionality related to diagnostics, health checks, plugins, initialisation hooks, service introspection, and more.
  termsOfService: https://www.localstack.cloud/legal/tos
  title: REST API for Community Aws localstack API
  version: latest
servers:
- url: http://{host}:{port}
  variables:
    port:
      default: '4566'
    host:
      default: localhost.localstack.cloud
tags:
- name: localstack
paths:
  /_localstack/config:
    get:
      description: Get current LocalStack configuration
      operationId: get_config
      tags:
      - localstack
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
          description: Current LocalStack configuration
        '404':
          description: Not found
    post:
      description: Configuration option to update with new value
      operationId: update_config_option
      tags:
      - localstack
      requestBody:
        content:
          application/json:
            schema:
              additionalProperties: false
              properties:
                value:
                  type:
                  - number
                  - string
                variable:
                  pattern: ^[_a-zA-Z0-9]+$
                  type: string
              required:
              - variable
              - value
              type: object
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                additionalProperties: false
                properties:
                  value:
                    type:
                    - number
                    - string
                  variable:
                    type: string
                required:
                - variable
                - value
                type: object
          description: Configuration option is updated
        '400':
          content:
            application/json: {}
          description: Bad request
        '404':
          description: Not found
  /_localstack/diagnose:
    get:
      description: Get diagnostics report
      operationId: get_diagnostics
      tags:
      - localstack
      responses:
        '200':
          content:
            application/json:
              schema:
                additionalProperties: false
                properties:
                  config:
                    type: object
                  docker-dependent-image-hashes:
                    type: object
                  docker-dependent-image-hosts:
                    type: object
                  docker-inspect:
                    type: object
                  file-tree:
                    type: object
                  important-endpoints:
                    type: object
                  info:
                    $ref: '#/components/schemas/SessionInfo'
                  logs:
                    additionalProperties: false
                    properties:
                      docker:
                        type: string
                    required:
                    - docker
                    type: object
                  services:
                    type: object
                  usage:
                    type: object
                  version:
                    additionalProperties: false
                    properties:
                      host:
                        additionalProperties: false
                        properties:
                          kernel:
                            type: string
                        required:
                        - kernel
                        type: object
                      image-version:
                        additionalProperties: false
                        properties:
                          created:
                            type: string
                          id:
                            type: string
                          sha256:
                            type: string
                          tag:
                            type: string
                        required:
                        - id
                        - sha256
                        - tag
                        - created
                        type: object
                      localstack-version:
                        additionalProperties: false
                        properties:
                          build-date:
                            type:
                            - string
                            - 'null'
                          build-git-hash:
                            type:
                            - string
                            - 'null'
                          build-version:
                            type:
                            - string
                            - 'null'
                        required:
                        - build-date
                        - build-git-hash
                        - build-version
                        type: object
                    required:
                    - image-version
                    - localstack-version
                    - host
                    type: object
                required:
                - version
                - info
                - services
                - config
                - docker-inspect
                - docker-dependent-image-hosts
                - file-tree
                - important-endpoints
                - logs
                - usage
                type: object
          description: Diagnostics report
  /_localstack/health:
    get:
      description: Get available LocalStack features and AWS services
      operationId: get_features_and_services
      tags:
      - localstack
      parameters:
      - allowEmptyValue: true
        in: query
        name: reload
        required: false
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                additionalProperties: false
                properties:
                  edition:
                    enum:
                    - community
                    - pro
                    - enterprise
                    - unknown
                    type: string
                  features:
                    type: object
                  services:
                    type: object
                  version:
                    type: string
                required:
                - edition
                - services
                - version
                type: object
          description: Available LocalStack features and AWS services
    head:
      tags:
      - localstack
      operationId: health
      responses:
        '200':
          content:
            text/plain: {}
          description: ''
    post:
      description: Restart or terminate LocalStack session
      operationId: manage_session
      tags:
      - localstack
      requestBody:
        content:
          application/json:
            schema:
              additionalProperties: false
              properties:
                action:
                  enum:
                  - restart
                  - kill
                  type: string
              required:
              - action
              type: object
        description: Action to perform
        required: true
      responses:
        '200':
          content:
            text/plain: {}
          description: Action was successful
        '400':
          content:
            text/plain: {}
          description: Bad request
    put:
      description: Store arbitrary data to in-memory state
      operationId: store_data
      tags:
      - localstack
      requestBody:
        content:
          application/json:
            schema:
              type: object
        description: Data to save
      responses:
        '200':
          content:
            application/json:
              schema:
                additionalProperties: false
                properties:
                  status:
                    type: string
                required:
                - status
                type: object
          description: Data was saved
  /_localstack/info:
    get:
      description: Get information about the current LocalStack session
      operationId: get_session_info
      tags:
      - localstack
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SessionInfo'
          description: Information about the current LocalStack session
  /_localstack/init:
    get:
      description: Get information about init scripts
      operationId: get_init_script_info
      tags:
      - localstack
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InitScripts'
          description: Information about init scripts
  /_localstack/init/{stage}:
    get:
      description: Get information about init scripts in a specific stage
      operationId: get_init_script_info_stage
      tags:
      - localstack
      parameters:
      - in: path
        name: stage
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InitScriptsStage'
          description: Information about init scripts in a specific stage
        '404':
          content:
            text/plain:
              schema:
                type: string
          description: Stage not found
  /_localstack/plugins:
    get:
      description: ''
      operationId: get_plugins
      tags:
      - localstack
      responses:
        '200':
          content:
            application/json: {}
          description: ''
  /_localstack/usage:
    get:
      description: ''
      operationId: get_usage
      tags:
      - localstack
      responses:
        '200':
          content:
            application/json: {}
          description: ''
components:
  schemas:
    SessionInfo:
      additionalProperties: false
      properties:
        edition:
          type: string
        is_docker:
          type: boolean
        is_license_activated:
          type: boolean
        machine_id:
          type: string
        server_time_utc:
          type: string
        session_id:
          type: string
        system:
          type: string
        uptime:
          type: integer
        version:
          type: string
      required:
      - version
      - edition
      - is_license_activated
      - session_id
      - machine_id
      - system
      - is_docker
      - server_time_utc
      - uptime
      type: object
    InitScriptsStage:
      additionalProperties: false
      properties:
        completed:
          type: boolean
        scripts:
          items:
            additionalProperties: false
            properties:
              name:
                type: string
              stage:
                type: string
              state:
                type: string
            required:
            - stage
            - name
            - state
            type: object
          type: array
      required:
      - completed
      - scripts
      type: object
    InitScripts:
      additionalProperties: false
      properties:
        completed:
          additionalProperties: false
          properties:
            BOOT:
              type: boolean
            READY:
              type: boolean
            SHUTDOWN:
              type: boolean
            START:
              type: boolean
          required:
          - BOOT
          - START
          - READY
          - SHUTDOWN
          type: object
        scripts:
          items:
            additionalProperties: false
            properties:
              name:
                type: string
              stage:
                type: string
              state:
                type: string
            required:
            - stage
            - name
            - state
            type: object
          type: array
      required:
      - completed
      - scripts
      type: object
externalDocs:
  description: LocalStack Documentation
  url: https://docs.localstack.cloud
